dist: bionic
language: csharp
mono: none
branches:
  except:
    - /^\d{14}\.[0-9a-f]{7}$/
script:
  - export DOTNET_SDK_URL=https://download.visualstudio.microsoft.com/download/pr/886b4a4c-30af-454b-8bec-81c72b7b4e1f/d1a0c8de9abb36d8535363ede4a15de6/dotnet-sdk-3.0.100-linux-x64.tar.gz
  - mkdir -p /opt/dotnet
  - curl -SL $DOTNET_SDK_URL | tar xz -C /opt/dotnet
  - export PATH=/opt/dotnet:$PATH
  - dotnet restore
  - dotnet publish -c Release -r linux-x64 -o dist-linux /p:PublishSingleFile=true /p:PublishTrimmed=true
  - dotnet publish -c Release -r win-x64   -o dist-win64 /p:PublishSingleFile=true /p:PublishTrimmed=true
  - dotnet publish -c Release -r win-x86   -o dist-win32 /p:PublishSingleFile=true /p:PublishTrimmed=true
  - dotnet publish -c Release -r osx-x64   -o dist-macos /p:PublishSingleFile=true /p:PublishTrimmed=true
before_deploy:
  - export PROJ=lyc.xuming.studio.api
  - export _TAG="`TZ='Asia/Shanghai' date +'%Y%m%d%H%M%S'`.`git log --format=%h -1`"
  - chmod +x ./dist-linux/$PROJ ./dist-macos/$PROJ
  - mv dist-linux $PROJ && tar cJf $PROJ.linux.$_TAG.tar.xz $PROJ && rm -rf $PROJ
  - mv dist-win64 $PROJ && tar cJf $PROJ.win64.$_TAG.tar.xz $PROJ && rm -rf $PROJ
  - mv dist-win32 $PROJ && tar cJf $PROJ.win32.$_TAG.tar.xz $PROJ && rm -rf $PROJ
  - mv dist-macos $PROJ && tar cJf $PROJ.macos.$_TAG.tar.xz $PROJ && rm -rf $PROJ
  - git tag "$_TAG"
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - $PROJ.linux.$_TAG.tar.xz
    - $PROJ.win64.$_TAG.tar.xz
    - $PROJ.win32.$_TAG.tar.xz
    - $PROJ.macos.$_TAG.tar.xz