language: csharp
mono: none
dotnet: 2.2.301
branches:
  except:
    - /^\d{14}\.[0-9a-f]{7}$/
script:
  - dotnet restore
  - dotnet publish -c Release -r linux-x64 -o dist-linux
  - dotnet publish -c Release -r win-x64   -o dist-win64
  - dotnet publish -c Release -r win-x86   -o dist-win32
  - dotnet publish -c Release -r osx-x64   -o dist-macos
before_deploy:
  - export PROJ=lyc.xuming.studio.api
  - export _TAG="`TZ='Asia/Shanghai' date +'%Y%m%d%H%M%S'`.`git log --format=%h -1`"
  - chmod +x ./dist-linux/$PROJ ./dist-macos/$PROJ
  - mv dist-linux $PROJ && tar cJf $PROJ.linux.$_TAG.tar.xz $PROJ && rm -rf $PROJ
  - mv dist-win64 $PROJ && tar cJf $PROJ.win64.$_TAG.tar.xz $PROJ && rm -rf $PROJ
  - mv dist-win32 $PROJ && tar cJf $PROJ.win32.$_TAG.tar.xz $PROJ && rm -rf $PROJ
  - mv dist-macos $PROJ && tar cJf $PROJ.macos.$_TAG.tar.xz $PROJ && rm -rf $PROJ
  - git tag "$_TAG"
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - $PROJ.linux.$_TAG.tar.xz
    - $PROJ.win64.$_TAG.tar.xz
    - $PROJ.win32.$_TAG.tar.xz
    - $PROJ.macos.$_TAG.tar.xz