language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      dotnet: 2.0.0-preview1-005977
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 2.0.0-preview1-005977

script:
  - dotnet restore
  - dotnet build -c Release
