name: Code analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: InferSharp
      uses: microsoft/infersharpaction@v1.4
      id: runinfersharp
      with:
        binary-path: obj
    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
